<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sh_scoutnet_webservice"
 *
 * Auto generated by Extension Builder 2015-02-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

/** @var string $_EXTKEY */
$EM_CONF[$_EXTKEY] = [
	'title' => 'Official Scoutnet Webservice class',
	'description' => 'This class is needed to comunicate with the scoutnet server.',
	'category' => 'services',
	'author' => 'Stefan "Mütze" Horst',
	'author_email' => 'muetze@scoutnet.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '3.0.2',
	'constraints' => [
		'depends' => [
			'typo3' => '9.0.0-9.5.99',
		],
		'conflicts' => [],
		'suggests' => [],
	],
];
