<?php
/**
 * Copyright (c) 2005-2024 Stefan (Mütze) Horst
 *
 * I don't have the time to read through all the licences to find out
 * what they exactly say. But it's simple. It's free for non-commercial
 * projects, but as soon as you make money with it, I want my share :-)
 * (License: Free for non-commercial use)
 *
 * Authors: Stefan (Mütze) Horst <muetze@scoutnet.de>
 */

namespace ScoutNet\ShScoutnetWebservice\Tests\Unit\Helpers;

use Prophecy\Prophet;
use ScoutNet\Api\Exceptions\ScoutNetException;
use ScoutNet\Api\Helpers\AESHelper;
use TYPO3\TestingFramework\Core\Unit\UnitTestCase;

class AESHelperTest extends UnitTestCase
{
    private Prophet $prophet;

    public function setup(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->prophet = new Prophet();
    }

    protected function tearDown(): void
    {
        $this->prophet->checkPredictions();
    }

    /**
     * @throws ScoutNetException
     */
    public function testEncryptDecrypt(): void
    {
        $key = [
            'key' => '12345678901234567890123456789012',
            'iv' => '1234567890123456',
            'mode' => 'CBC',
        ];

        $pt = 'testtest';

        $aes = new AESHelper($key['key'], $key['mode'], $key['iv']);

        $crypt = $aes->encrypt($pt);

        $aes = new AESHelper($key['key'], $key['mode'], $key['iv']);

        self::assertEquals($pt, $aes->decrypt($crypt));
    }

    public static function dataProviderCorrectKeyLength(): array
    {
        return [
            'aes128' => [
                '1234567890123456',
            ],
            'aes192' => [
                '123456789012345678901234',
            ],
            'aes256' => [
                '12345678901234567890123456789012',
            ],
            'empty' => [
                '',
                [1572194460],
            ],
            'wrong length' => [
                '123',
                [1572194460],
            ],
        ];
    }

    /**
     * @param string $key
     * @param array $expExceptions
     *
     * @throws ScoutNetException
     * @dataProvider dataProviderCorrectKeyLength
     */
    public function testCorrectKeyLength(string $key, array $expExceptions = []): void
    {
        if ($expExceptions and count($expExceptions) > 0) {
            foreach ($expExceptions as $expExc) {
                $this->expectExceptionCode($expExc);
            }
        }
        new AESHelper($key);
    }

    public static function dataProviderEncrypt(): array
    {
        return [
            'short iv' => [ // should be padded with 0x00
                [
                    'key' => '12345678901234567890123456789012',
                    'iv' => '1234567890123', // will be padded by 0x00
                    'mode' => 'CBC',
                ],
                'testtest',
                'CZSjsb+lRidyF3vAYKbbzA==', // pkcs#7
                // 'zckkIjpRYuWW19m0QtvxTw==', // zero padded
            ],
            'short block' => [ // should be padded with 0x00
                [
                    'key' => '12345678901234567890123456789012',
                    'iv' => '1234567890123456',
                    'mode' => 'CBC',
                ],
                'testtest',
                'FCbM1hpe5vAbYvq3LQv5yg==', // pkcs#7
                // 'ruIH7F3mHozAP9aU5cZD1A==', // zero padded
            ],
            'no padding' => [
                [
                    'key' => '12345678901234567890123456789012',
                    'iv' => '1234567890123456',
                    'mode' => 'CBC',
                ],
                'testtesttesttest',
                'O4p8xIJFm5/EHinKjrB/U5WyJAFMhVe4NbeHe514eOw=', // pkcs#7
                // 'O4p8xIJFm5/EHinKjrB/Uw==', // no padding
            ],
            'more than one block' => [
                [
                    'key' => '12345678901234567890123456789012',
                    'iv' => '1234567890123456',
                    'mode' => 'CBC',
                ],
                'testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest',
                'O4p8xIJFm5/EHinKjrB/U8ySfWjP9s0J3fTbi3/0LcXmNVWbRvcvaCin63IuFcOE9Cg6nQylpSabUfW9m/WO+8r87PO7U2P/JcqN8lSzoErLoVmPjYF3YM0AgAGTCk6ns5JWKJ/gvJC3FhmA8Tmw8OpbXuKosGDU2kZRrzHKMkk=', // pkcs#7
                // 'O4p8xIJFm5/EHinKjrB/U8ySfWjP9s0J3fTbi3/0LcXmNVWbRvcvaCin63IuFcOE9Cg6nQylpSabUfW9m/WO+8r87PO7U2P/JcqN8lSzoErLoVmPjYF3YM0AgAGTCk6ns5JWKJ/gvJC3FhmA8Tmw8LYp1olEN+pE8rhBu5yG328=', // zero padding
            ],
        ];
    }

    /**
     * @dataProvider dataProviderEncrypt
     *
     * @param array $key
     * @param string $plaintext
     * @param string $cyphertext
     *
     * @throws ScoutNetException
     */
    public function testEncrypt(array $key, string $plaintext, string $cyphertext): void
    {
        $aes = new AESHelper($key['key'], $key['mode'], $key['iv']);
        $crypt = base64_encode($aes->encrypt($plaintext));

        self::assertEquals($cyphertext, $crypt);
    }

    public static function dataProviderDecrypt(): array
    {
        return [
            'less than one block' => [
                [
                    'key' => '12345678901234567890123456789012',
                    'iv' => '1234567890123456',
                    'mode' => 'CBC',
                ],
                'FCbM1hpe5vAbYvq3LQv5yg==', // pkcs#7
                // 'ruIH7F3mHozAP9aU5cZD1A==', // zero padded
                'testtest',
            ],
            'not aligned - less than one block' => [
                [
                    'key' => '12345678901234567890123456789012',
                    'iv' => '1234567890123456',
                    'mode' => 'CBC',
                ],
                'ruIH7F3mHozAP9aU5cZD', // missing chars
                '', // error in decoding
                // base64_decode('bih5rTSfnoaUeGjstwajBA=='),
            ],
            'exact one block' => [
                [
                    'key' => '12345678901234567890123456789012',
                    'iv' => '1234567890123456',
                    'mode' => 'CBC',
                ],
                'O4p8xIJFm5/EHinKjrB/U5WyJAFMhVe4NbeHe514eOw=', // pkcs#7
                // 'O4p8xIJFm5/EHinKjrB/Uw==', // no padding
                'testtesttesttest',
            ],
            'more than one block' => [
                [
                    'key' => '12345678901234567890123456789012',
                    'iv' => '1234567890123456',
                    'mode' => 'CBC',
                ],
                'O4p8xIJFm5/EHinKjrB/U8ySfWjP9s0J3fTbi3/0LcXmNVWbRvcvaCin63IuFcOE9Cg6nQylpSabUfW9m/WO+8r87PO7U2P/JcqN8lSzoErLoVmPjYF3YM0AgAGTCk6ns5JWKJ/gvJC3FhmA8Tmw8OpbXuKosGDU2kZRrzHKMkk=', // pkcs#7 padding
                // 'O4p8xIJFm5/EHinKjrB/U8ySfWjP9s0J3fTbi3/0LcXmNVWbRvcvaCin63IuFcOE9Cg6nQylpSabUfW9m/WO+8r87PO7U2P/JcqN8lSzoErLoVmPjYF3YM0AgAGTCk6ns5JWKJ/gvJC3FhmA8Tmw8LYp1olEN+pE8rhBu5yG328=', // zero padding
                'testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest',
            ],
            //            'broken length' => [
            //                [
            //                    'key' => '12345678901234567890123456789012',
            //                    'iv' => '1234567890123456',
            //                    'mode' => 'CBC',
            //                ],
            //                'O4p8xIJFm5/EHinKjrB/U8ySfWjP9s0J3fTbi3/0LcXmNVWbRvcvaCin63IuFcOE9Cg6nQylpSabUfW9m/WO+8r87PO7U2P/JcqN8lSzoErLoVmPjYF3YM0AgAGTCk6ns5JWKJ/gvJC3FhmA8Tmw8OpbXuKosGDU2kZRrzHKMk',
            //                false,
            //            ],
        ];
    }

    /**
     * @dataProvider dataProviderDecrypt
     *
     * @param array $key
     * @param string $cyphertext
     * @param string $plaintext
     *
     * @throws ScoutNetException
     */
    public function testDecrypt(array $key, string $cyphertext, string $plaintext): void
    {
        $aes = new AESHelper($key['key'], $key['mode'], $key['iv']);
        $plain = $aes->decrypt(base64_decode($cyphertext));

        self::assertEquals($plaintext, $plain);
    }
}
